### ISSUE TITLE
Deserialization does not wire up bidirectional relationships properly

### ISSUE THREAD

**Issue by robfletcher** [robfletcher/grails-gson#24]
When instances are deserialized the reverse side of the relationship needs to be assigned (or appropriate _addTo_ method used). Otherwise the binding succeeds & _validate / save_ appear to work but an exception is thrown when the session is flushed.

I thought since I'm using `DataBindingUtils.bindObjectToDomainInstance` this would be handled properly but it does not appear to be the case. The test app wasn't catching the problem as the _Album -> Artist_ relationship isn't bidirectional.

**Comment by robfletcher** [comment]
Fixed, although there are some issues with changing contents of persistent collection. See #25

**Comment by sumitgogia** [comment]
I am seeing the opposite problem i.e. due to this fix, a (potentially large) collection is loaded without any reason. E.g. consider the following domains

``` groovy
class App {
    String name
    static hasMany = [installs: UserApp]
}

class UserApp {
    int playCount
    static belongsTo = [app: App]
    static mapping = {
        app fetch: "join"
    }
}
```

Attempting to update a userApp instance results in loading of all the app installs. This **does not** happen when using the default grails data binding.

``` groovy
    def data = [id: 1, playCount: 1]
    def json = gson.toJson(params)
    def ua1 = gson.fromJson(json, UserApp)//<- loads ua1.app.installs collection
    ua1.save(flush: true, failOnError: true)
```

The problematic code is the bindOwner method in GrailsDomainDeserializer. Should it check to see if the association/collection is initialized/loaded before attempting to bind the other side?

Otherwise, is it possible to optionally disable this fix? (I haven't noticed the problem for which this ticket was created)
