### ISSUE TITLE
NPE when domain is a HibernateProxy

### ISSUE THREAD

**Issue by wellsst** [robfletcher/grails-gson#41]
Using GSON 1.1.4 on Grails 2.1.4

Doing this:
render someInstance as GSON

was producing "cannot get identifier() on null object" in  GrailsDomainSerializer.groovy
@ line 71: iterator(domainClass.identifier)

Seems due to a "belongsTo" on the "someInstance" having the classname as a "packageName.DomainName_$$_javassist_5" indicating this is a HibernateProxy

The fix I applied locally is in GrailsDomainSerializer.groovy line 82:

```
private GrailsDomainClass getDomainClassFor(T instance) {
    // TODO: may need to cache this

    grailsApplication.getDomainClass(getClassOfDomain(instance).name)
```

   }

```
 private Class getClassOfDomain(T instance) {
    instance instanceof HibernateProxy ? ((HibernateProxy) instance).getHibernateLazyInitializer().getImplementation().class : instance.class
 }
```

and line 33:
       def field = getClassOfDomain(instance).getDeclaredField(property.name)

Sorry about the code inline here I am totally new to git.

**Comment by dipayanb** [comment]
This is exactly the same problem that I have faced today. This is a problem which has been already fixed in the Pull request of Naresha done on 12-May-2013. You can check The commits to the repository.

I am new to grails and I don't know how to include the latest code in the repository to the grails project. The default downloading of the plugin using the BuildConfig.groovy route fetches the old code. 

For the time being I have manually changed the code in the GrailsDomainSerializer.groovy file and things are working for the time being until the plugin version is bumped up.

**Comment by sergiomichels** [comment]
Same issue here...

**Comment by sergiomichels** [comment]
I'm pretty sure that this can be closed. Tried with the 1.2-SNAPSHOT version and the error didn't occurred.

**Comment by robfletcher** [comment]
Ok, thanks. Closing.
